# Generated by Django 4.2 on 2023-05-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_mag', '0005_contactrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
    ]
