# Generated by Django 4.2 on 2023-05-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_mag', '0009_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('extra small', 'XS'), ('small', 'S'), ('medium', 'M'), ('large', 'L'), ('extra large', 'XL'), ('extra extra large', 'XXL')], max_length=20)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_mag.item')),
            ],
        ),
    ]
